### ISSUE TITLE
not working with example data

### ISSUE THREAD

**Issue by RonghuiZhou** [KristapsE/DP4-AI#50]
I tried with the example data downloaded from here:
https://www.repository.cam.ac.uk/handle/1810/303161

I picked MM:
![image](https://user-images.githubusercontent.com/56187916/114463080-f2cd7580-9bb1-11eb-820a-f7f902fdb1fd.png)

Error occurred:
![image](https://user-images.githubusercontent.com/56187916/114463144-0bd62680-9bb2-11eb-9da1-96060bb3213f.png)

Any advice? Thanks.

**Comment by KristapsE** [comment]
This is odd. The error message arises simply because you don't have MacroModel, or have it, but without a valid license. But this still shouldn't cause problems with the paper data, as I believe the workflow should skip all computational processes if the results are already done. 

Could it be a GUI quirk, @HowarthA ?

**Comment by HowarthA** [comment]
DP4-AI now runs with the exact settings you have entered in the GUI. In addition, make sure to set the Output Folder to the location where the output files are on your machine. Equivalently you can launch PyDP4_GUI.py from the folder containing the calculations as the working directory.

**Comment by RonghuiZhou** [comment]
Thanks, what do you mean "make sure to set the Output Folder to the location where the output files are on your machine"? Is it the same as the sample data or different empty location? I am also not sure "Equivalently you can launch PyDP4_GUI.py from the folder containing the calculations as the working directory."

**Comment by RonghuiZhou** [comment]
why the issue is closed? I am still not able to run it.

**Comment by RonghuiZhou** [comment]
By the way, there is always a message like this why unzipping the data. Any idea? Thanks.

![image](https://user-images.githubusercontent.com/56187916/114492691-0f37d500-9be7-11eb-9f69-8f1f833383c9.png)

**Comment by HowarthA** [comment]
> why the issue is closed? I am still not able to run it.

There is no issue with the code here, DP4-AI is running perfectly fine with the example data. 

- to use DP4-AI with pre-run DFT/MM calculations you have to indicate to the program where the output files from those calculations are.  
- the best way to do this is to use the "Output Folder" dialogue in the GUI 
- otherwise, DP4-AI assumes these files are in the current working directory, which means you can equivalently navigate to where the files are in your terminal prior to launching PyDP4_GUI.py

with the settings you have selected, DP4-AI will run and exit almost immediately. Check "DP4 statistics" to view the output of this calculation.

**Comment by RonghuiZhou** [comment]
Thank you. Can you please show the file structure? Where should I indicate the "Output Folder"? There is no such folder in the example data. Where is the "DP4 statistics"?

**Comment by RonghuiZhou** [comment]
Would it be possible to have a Zoom or Teams meeting to help me sort this out? Thank you.
